
language: node_js
node_js:
  - stable
env:
  - ENVIRONMENT=DEVELOPMENT
cache:
  directories:
    - node_modules
services: mongodb
jobs:
  include:
    - stage: "API Testing"
      script: npm run test

    - stage: "Deploy to Heroku"
      script: cd view && npm i && npm run build --prod && cp -r build ../ && cd ../
      cache:
        directories:
          - node_modules

      deploy:
        provider: heroku
        api_key: b9f62087-1916-4eec-ad15-dc7d296f7299
        app: intense-reef-03949
      
      on:
        repo: OneArmyj/CS3219_TaskB
      skip_cleanup: true